### ISSUE TITLE
Feedback for v1.1

### ISSUE THREAD

**Issue by etjk** [CS2103-AY1819S1-W17-2/main#80]
- [x] Remove [W.I.P] tag
- [x] Include responsibility 
(UI, Git,  Code consistency, storage, testing, integration, model, deliverables and deadline)
- [x] Elaborate on User Guide introduction

Reference from https://github.com/nus-cs2103-AY1819S1/addressbook-level4/pull/21
- [x] Developer guide [Delete module > Use case > Extension](https://github.com/CS2103-AY1819S1-W17-2/main/blob/master/docs/DeveloperGuide.adoc#use-case-delete-module)
- [x] Developer guide [Product Survey](https://github.com/CS2103-AY1819S1-W17-2/main/blob/master/docs/DeveloperGuide.adoc#appendix-g-product-survey
)
- [x] Developer guide [Non functional requirements](https://github.com/CS2103-AY1819S1-W17-2/main/blob/master/docs/DeveloperGuide.adoc#appendix-e-non-functional-requirements)
- [x] User guide [addon description (Description and format)](https://github.com/CS2103-AY1819S1-W17-2/main/blob/master/docs/UserGuide.adoc#32-adding-a-module-addon-wip)
- [x] User guide [remove description (Description and format)](https://github.com/CS2103-AY1819S1-W17-2/main/blob/master/docs/UserGuide.adoc#33-deleting-a-module-remove-wip)
- [x] User guide [load command(format)](https://github.com/CS2103-AY1819S1-W17-2/main/blob/master/docs/UserGuide.adoc#36-loading-module-configurations-load-coming-in-v20
)
- [x] User guide [save command(description)](
https://github.com/CS2103-AY1819S1-W17-2/main/blob/master/docs/UserGuide.adoc#35-saving-module-configurations-save)
